# SOPS Configuration
# Defines encryption rules for secrets management
keys:
  # Age keys for encryption
  - &admin_key age106yg6v2r2wal77evhkthsft2x4uducdxj4ds9ax7x6tvngtyas7skgy8km

creation_rules:
  # Global secrets (accessible by all systems)
  - path_regex: secrets/global/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  # User-specific secrets
  - path_regex: secrets/users/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  # Host-specific secrets
  - path_regex: secrets/hosts/apollo/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  - path_regex: secrets/hosts/theia/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  - path_regex: secrets/hosts/macbook-pro/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  - path_regex: secrets/hosts/macbook-air/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  # Service-specific secrets
  - path_regex: secrets/services/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  # Development secrets (less restrictive)
  - path_regex: secrets/development/.*\.yaml$
    key_groups:
      - age:
          - *admin_key