name: Test NixOS Configuration
on: [push, pull_request]

jobs:
  test-flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [nebula]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Test flake
      run: |
        nix flake check
        echo "Building configuration: ${{ matrix.config }}"
        nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel